dependencies:
- spyder 5.0.3
- cython
- matplotlib
- pandas
- pillow
- scikit-learn
- scipy
- sympy
# This is to avoid pulling an older IPython version, which prints
# unnecessary warnings while using our debugger.
- ipython >=7.17

# This is required to avoid conda complaining about it.
- pip

# Required for jupyter-desktop-server
- websockify
- nbgitpuller
- pip:
    - jupyter-desktop-server
